Add initramfs and readonly rootfs
xen-troops/meta-aos-minimal pull request #10
Opened 2020-10-06 14:28 UTC by varder

2020-10-09 08:11 UTC, oleksiimoisieiev requested changes

2020-10-09 08:11 UTC, oleksiimoisieiev commented on recipes-core/images/aos-image-minimal.bb
> +    newinit = newinit.replace('ExecStart=/usr/sbin/quotaon -aug', 'ExecStartPre=/usr/sbin/quotacheck -avum \nExecStart=/usr/sbin/quotaon -avu')
Please user systemd-quotacheck default service to perform quotacheck

2020-10-09 08:39 UTC, oleksiimoisieiev commented on recipes-core/images/aos-image-minimal.bb
> +APPEND_append = '" ro"'
IMAGE_FEATURES_append = " read-only-rootfs"

2020-10-12 08:29 UTC, oleksiimoisieiev commented on recipes-core/systemd/systemd_%.bbappend
> +    sed -i -e "s/quotaon -aug/quotaon -avu/" \
I'd rather leave -aug. Preserving group is more important then verbosity.

2020-10-12 08:31 UTC, oleksiimoisieiev commented on recipes-extended/netconfig/netconfig.bb
> +pkg_postinst_${PN} () {
Could you please share the background of this change? I suppose this wouldn't be working as expected.

2020-10-21 12:26 UTC, oleksiimoisieiev approved these changes

2020-10-21 12:40 UTC, Eabramov84 approved these changes

2020-10-28 11:04 UTC, al1img commented
New PR will be submitted.

2020-10-28 11:04 UTC, closed without merging