Cni plugins
xen-troops/meta-aos-minimal pull request #14
Opened 2021-01-06 09:38 UTC by varder

2021-01-06 12:42 UTC, oleksiimoisieiev requested changes

2021-01-06 12:42 UTC, oleksiimoisieiev commented on recipes-networking/cni/dnsname/0001-resolve-local-hostnames.patch
> ++	"io/ioutil"
This change is unnecessary.

2021-01-06 12:42 UTC, oleksiimoisieiev commented on recipes-networking/cni/dnsname/0001-resolve-local-hostnames.patch
> +-
This change is unnecessary.

2021-01-06 13:03 UTC, oleksiimoisieiev commented on recipes-networking/cni/aos-firewall.bb
> +FILES_${PN} = "${libexecdir}/cni/"
use common variable for ${libexecdir}/cni/

2021-01-06 13:32 UTC, varder commented on recipes-networking/cni/aos-firewall.bb
> +    ${GO} build -o ${B}/bin/aos-firewall
It seems that makefile is redundant here. l suggest to update aos-firewall directory structure instead

2021-01-28 13:27 UTC, al1img commented
Added in meta-aos

2021-01-28 13:27 UTC, closed without merging